# Generated by KIF Data Manager

module GameData
  class << self
    alias kif_original_load_all load_all
    def load_all
      kif_original_load_all
      Species.register({
        :id => :TEST_MON,
        :name => "TestMon",
        :type1 => :NORMAL,
        :base_stats => { :HP => 100, :ATTACK => 100, :DEFENSE => 100, :SPECIAL_ATTACK => 100, :SPECIAL_DEFENSE => 100, :SPEED => 100 },
        :abilities => [  ],
        :hidden_abilities => [  ],
        :moveset => [
        ],
      })
    end
  end
end
